name: covid19_web
description: Covid19 DASHBOARD
version: 1.0.0
# homepage: 
author: Adel BEN HAMADI <benhamadi.adel@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  angular_forms: ^3.0.0           
  angular_router: ^2.0.0
  firebase: ^8.0.0
  #get_it:
  chartjs: ^0.5.2
  biscuits: ^2.8.0
  encrypt: ^4.1.0
  dialog: ^0.7.2
  intl: ^0.16.1
  csv: ^4.1.0
  dwds: ^7.1.1

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_web_compilers: ^2.12.2
  #sass_builder: ^2.1.2
  pedantic: ^1.9.2
  test: ^1.15.7

transformers:
  - $dart2js:
      minify: false
      sourceMaps: true
      suppressHints: false
      suppressWarnings: true
      terse: true
      verbose: true
 